social_auth_facebook.settings:
  type: config_object
  label: 'Simple FB Connect settings'
  mapping:
    disabled_roles:
      type: sequence
      sequence:
        type: string
        label: 'Disable FB login for the following roles'
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'App Secret'
    graph_version:
      type: float
      label: 'Facebook Graph API version'
    post_login_path:
      type: string
      label: 'Post login path'
    redirect_user_form:
      type: integer
      label: 'Redirect new users to Drupal user form'
    disable_admin_login:
      type: integer
      label: 'Disable FB login for administrator'
